name: "Test Custom Actions"
description: "Testing Custom Actions"
inputs:
  greet-name:
    description: "Greeter Name"
    required: true
    default: "GitHub"
outputs:
  random:
    description: "Random Number"
    value: ${{ steps.random-number-generator.outputs.random }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "HELLO $INPUT_GREET_NAME"
      shell: bash
      env:
        INPUT_GREET_NAME: ${{inputs.greet-name}}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Set Github Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{github.action_path}}